export const LABELS = {
  "en": {
    "title": "Ride history",
    "refresh": "Read locally",
    "cloud_detail": "Get cloud detail",
    "coverage": "Recorded subset; completeness unverified",
    "empty": "No recorded rides in this range",
    "read_error": "Read failed. Read locally again or narrow the dates.",
    "detail_error": "Cloud detail unavailable. Try again later.",
    "loading": "Reading…",
    "next": "Next page",
    "page": "Page",
    "local": "Local archive",
    "cloud": "Cloud detail",
    "samples": "Speed sample values · units unverified",
    "unknown_units": "Electricity usage · unit unverified",
    "observed": "Observed",
    "denied": "Access denied",
    "distance": "Distance",
    "duration": "Duration",
    "max_speed": "Maximum speed",
    "avg_speed": "Average speed",
    "energy": "Energy",
    "start": "Start",
    "end": "End",
    "start_date": "Start date",
    "end_date": "End date",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Missing months",
    "partial": "Partial months",
    "unknown": "Unknown months",
    "source_fields": "Source field",
    "energy_intensity": "Last ride energy consumption per distance",
    "track_points": "Track points",
    "distance_samples": "Point distance values · units unverified"
  },
  "zh-Hans": {
    "title": "行程历史",
    "refresh": "本地读取",
    "cloud_detail": "获取云端详情",
    "coverage": "已记录的部分历史；完整性未确认",
    "empty": "此范围内没有已记录行程",
    "read_error": "读取失败，请重新本地读取或缩小日期范围。",
    "detail_error": "云端详情暂不可用，请稍后重试。",
    "loading": "读取中…",
    "next": "下一页",
    "page": "第",
    "local": "本地档案",
    "cloud": "云端详情",
    "samples": "速度采样值 · 单位未确认",
    "unknown_units": "用电量 · 单位未确认",
    "observed": "采样时间",
    "denied": "没有读取权限",
    "distance": "里程",
    "duration": "时长",
    "max_speed": "最高速度",
    "avg_speed": "平均速度",
    "energy": "耗能",
    "start": "开始",
    "end": "结束",
    "start_date": "开始日期",
    "end_date": "结束日期",
    "cursor_error": "续查游标过期、被缓存预算回收或不属于当前车辆和范围，请重新查询。",
    "ride_id": "行程 ID",
    "missing": "缺月",
    "partial": "部分月份",
    "unknown": "未知月份",
    "source_fields": "来源字段",
    "energy_intensity": "最近行程单位里程能耗",
    "track_points": "轨迹点数",
    "distance_samples": "点间距离曲线 · 单位待验证"
  },
  "zh-Hant": {
    "title": "行程歷史",
    "refresh": "本機讀取",
    "cloud_detail": "取得雲端詳情",
    "coverage": "已記錄的部分歷史；完整性未確認",
    "empty": "此範圍內沒有已記錄行程",
    "read_error": "讀取失敗，請重新本機讀取或縮小日期範圍。",
    "detail_error": "雲端詳情暫不可用，請稍後重試。",
    "loading": "讀取中…",
    "next": "下一頁",
    "page": "第",
    "local": "本機檔案",
    "cloud": "雲端詳情",
    "samples": "速度採樣值 · 單位未確認",
    "unknown_units": "用電量 · 單位未確認",
    "observed": "採樣時間",
    "denied": "沒有讀取權限",
    "distance": "距離",
    "duration": "騎行時長",
    "max_speed": "最高速度",
    "avg_speed": "平均速度",
    "energy": "能耗",
    "start": "開始時間",
    "end": "結束時間",
    "start_date": "開始日期",
    "end_date": "結束日期",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "缺月",
    "partial": "部分月份",
    "unknown": "未知月份",
    "source_fields": "Source field",
    "energy_intensity": "上次行程: 單位里程能耗",
    "track_points": "軌跡點數",
    "distance_samples": "點間距離曲線 · 單位待驗證"
  },
  "de": {
    "title": "Fahrtenhistorie",
    "refresh": "Lokal lesen",
    "cloud_detail": "Cloud-Details abrufen",
    "coverage": "Gespeicherter Ausschnitt; Vollständigkeit unbestätigt",
    "empty": "Keine gespeicherten Fahrten in diesem Zeitraum",
    "read_error": "Lesen fehlgeschlagen. Lokal neu lesen oder Zeitraum verkleinern.",
    "detail_error": "Cloud-Details nicht verfügbar. Später erneut versuchen.",
    "loading": "Wird gelesen…",
    "next": "Nächste Seite",
    "page": "Seite",
    "local": "Lokales Archiv",
    "cloud": "Cloud-Details",
    "samples": "Geschwindigkeitsproben · Einheit unbestätigt",
    "unknown_units": "Stromverbrauch · Einheit unbestätigt",
    "observed": "Beobachtet",
    "denied": "Zugriff verweigert",
    "distance": "Strecke",
    "duration": "Fahrtdauer",
    "max_speed": "Höchstgeschwindigkeit",
    "avg_speed": "Durchschnittsgeschwindigkeit",
    "energy": "Energie",
    "start": "Startzeit",
    "end": "Endzeit",
    "start_date": "Startdatum",
    "end_date": "Enddatum",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Fehlende Monate",
    "partial": "Teilweise Monate",
    "unknown": "Unbekannte Monate",
    "source_fields": "Source field",
    "energy_intensity": "Letzte Fahrt: Energieverbrauch pro Strecke",
    "track_points": "Trackpunkte",
    "distance_samples": "Punktabstände · Einheit ungeprüft"
  },
  "fr": {
    "title": "Historique des trajets",
    "refresh": "Lire localement",
    "cloud_detail": "Obtenir les détails cloud",
    "coverage": "Historique partiel enregistré ; exhaustivité non vérifiée",
    "empty": "Aucun trajet enregistré dans cette période",
    "read_error": "Lecture impossible. Relire localement ou réduire la période.",
    "detail_error": "Détails cloud indisponibles. Réessayer plus tard.",
    "loading": "Lecture…",
    "next": "Page suivante",
    "page": "Page",
    "local": "Archive locale",
    "cloud": "Détails cloud",
    "samples": "Échantillons de vitesse · unité non vérifiée",
    "unknown_units": "Électricité utilisée · unité non vérifiée",
    "observed": "Observé",
    "denied": "Accès refusé",
    "distance": "Distance",
    "duration": "Durée des trajets",
    "max_speed": "Vitesse maximale",
    "avg_speed": "Vitesse moyenne",
    "energy": "Énergie",
    "start": "Heure de départ",
    "end": "Heure d’arrivée",
    "start_date": "Date de début",
    "end_date": "Date de fin",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Mois manquants",
    "partial": "Mois partiels",
    "unknown": "Mois inconnus",
    "source_fields": "Source field",
    "energy_intensity": "Dernier trajet: Consommation par distance",
    "track_points": "Points de trace",
    "distance_samples": "Distances entre points · unité non vérifiée"
  },
  "es": {
    "title": "Historial de viajes",
    "refresh": "Leer localmente",
    "cloud_detail": "Obtener detalles de nube",
    "coverage": "Historial parcial guardado; integridad sin verificar",
    "empty": "No hay viajes guardados en este intervalo",
    "read_error": "Lectura fallida. Leer de nuevo o reducir el intervalo.",
    "detail_error": "Detalles de nube no disponibles. Reintentar más tarde.",
    "loading": "Leyendo…",
    "next": "Página siguiente",
    "page": "Página",
    "local": "Archivo local",
    "cloud": "Detalles de nube",
    "samples": "Muestras de velocidad · unidad sin verificar",
    "unknown_units": "Electricidad usada · unidad sin verificar",
    "observed": "Observado",
    "denied": "Acceso denegado",
    "distance": "Distancia",
    "duration": "Duración de viajes",
    "max_speed": "Velocidad máxima",
    "avg_speed": "Velocidad media",
    "energy": "Energía",
    "start": "Hora de inicio",
    "end": "Hora de fin",
    "start_date": "Fecha inicial",
    "end_date": "Fecha final",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Meses faltantes",
    "partial": "Meses parciales",
    "unknown": "Meses desconocidos",
    "source_fields": "Source field",
    "energy_intensity": "Último viaje: Consumo por distancia",
    "track_points": "Puntos del recorrido",
    "distance_samples": "Distancias entre puntos · unidad sin verificar"
  },
  "it": {
    "title": "Cronologia viaggi",
    "refresh": "Leggi localmente",
    "cloud_detail": "Ottieni dettagli cloud",
    "coverage": "Cronologia parziale salvata; completezza non verificata",
    "empty": "Nessun viaggio registrato in questo intervallo",
    "read_error": "Lettura fallita. Rileggi localmente o riduci l’intervallo.",
    "detail_error": "Dettagli cloud non disponibili. Riprova più tardi.",
    "loading": "Lettura…",
    "next": "Pagina successiva",
    "page": "Pagina",
    "local": "Archivio locale",
    "cloud": "Dettagli cloud",
    "samples": "Campioni di velocità · unità non verificata",
    "unknown_units": "Elettricità usata · unità non verificata",
    "observed": "Osservato",
    "denied": "Accesso negato",
    "distance": "Distanza",
    "duration": "Durata dei viaggi",
    "max_speed": "Velocità massima",
    "avg_speed": "Velocità media",
    "energy": "Energia",
    "start": "Ora di partenza",
    "end": "Ora di arrivo",
    "start_date": "Data iniziale",
    "end_date": "Data finale",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Mesi mancanti",
    "partial": "Mesi parziali",
    "unknown": "Mesi sconosciuti",
    "source_fields": "Source field",
    "energy_intensity": "Ultimo viaggio: Consumo per distanza",
    "track_points": "Punti del percorso",
    "distance_samples": "Distanze tra punti · unità non verificata"
  },
  "pt": {
    "title": "Histórico de viagens",
    "refresh": "Ler localmente",
    "cloud_detail": "Obter detalhes da nuvem",
    "coverage": "Histórico parcial guardado; integridade não verificada",
    "empty": "Sem viagens guardadas neste intervalo",
    "read_error": "Falha de leitura. Volte a ler ou reduza o intervalo.",
    "detail_error": "Detalhes da nuvem indisponíveis. Tente mais tarde.",
    "loading": "A ler…",
    "next": "Página seguinte",
    "page": "Página",
    "local": "Arquivo local",
    "cloud": "Detalhes da nuvem",
    "samples": "Amostras de velocidade · unidade não verificada",
    "unknown_units": "Eletricidade utilizada · unidade não verificada",
    "observed": "Observado",
    "denied": "Acesso negado",
    "distance": "Distância",
    "duration": "Duração das viagens",
    "max_speed": "Velocidade máxima",
    "avg_speed": "Velocidade média",
    "energy": "Energia",
    "start": "Hora de início",
    "end": "Hora de fim",
    "start_date": "Data inicial",
    "end_date": "Data final",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Meses em falta",
    "partial": "Meses parciais",
    "unknown": "Meses desconhecidos",
    "source_fields": "Source field",
    "energy_intensity": "Última viagem: Consumo por distância",
    "track_points": "Pontos do percurso",
    "distance_samples": "Distâncias entre pontos · unidade não verificada"
  },
  "pt-BR": {
    "title": "Histórico de viagens",
    "refresh": "Ler localmente",
    "cloud_detail": "Obter detalhes da nuvem",
    "coverage": "Histórico parcial salvo; integridade não verificada",
    "empty": "Nenhuma viagem salva neste intervalo",
    "read_error": "Falha na leitura. Leia novamente ou reduza o intervalo.",
    "detail_error": "Detalhes da nuvem indisponíveis. Tente mais tarde.",
    "loading": "Lendo…",
    "next": "Próxima página",
    "page": "Página",
    "local": "Arquivo local",
    "cloud": "Detalhes da nuvem",
    "samples": "Amostras de velocidade · unidade não verificada",
    "unknown_units": "Eletricidade usada · unidade não verificada",
    "observed": "Observado",
    "denied": "Acesso negado",
    "distance": "Distância",
    "duration": "Duração das viagens",
    "max_speed": "Velocidade máxima",
    "avg_speed": "Velocidade média",
    "energy": "Energia",
    "start": "Hora de início",
    "end": "Hora de fim",
    "start_date": "Data inicial",
    "end_date": "Data final",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Meses ausentes",
    "partial": "Meses parciais",
    "unknown": "Meses desconhecidos",
    "source_fields": "Source field",
    "energy_intensity": "Última viagem: Consumo por distância",
    "track_points": "Pontos do percurso",
    "distance_samples": "Distâncias entre pontos · unidade não verificada"
  },
  "ru": {
    "title": "История поездок",
    "refresh": "Прочитать локально",
    "cloud_detail": "Получить детали из облака",
    "coverage": "Сохранена часть истории; полнота не подтверждена",
    "empty": "В этом диапазоне нет сохранённых поездок",
    "read_error": "Ошибка чтения. Прочитайте заново или сократите диапазон.",
    "detail_error": "Детали из облака недоступны. Попробуйте позже.",
    "loading": "Чтение…",
    "next": "Следующая страница",
    "page": "Страница",
    "local": "Локальный архив",
    "cloud": "Детали из облака",
    "samples": "Образцы скорости · единицы не проверены",
    "unknown_units": "Расход электричества · единицы не проверены",
    "observed": "Наблюдение",
    "denied": "Доступ запрещён",
    "distance": "Расстояние",
    "duration": "Продолжительность поездок",
    "max_speed": "Максимальная скорость",
    "avg_speed": "Средняя скорость",
    "energy": "Энергия",
    "start": "Время начала",
    "end": "Время окончания",
    "start_date": "Начальная дата",
    "end_date": "Конечная дата",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Отсутствующие месяцы",
    "partial": "Неполные месяцы",
    "unknown": "Неизвестные месяцы",
    "source_fields": "Source field",
    "energy_intensity": "Последняя поездка: Расход энергии на расстояние",
    "track_points": "Точки маршрута",
    "distance_samples": "Расстояния между точками · единицы не проверены"
  },
  "ja": {
    "title": "走行履歴",
    "refresh": "ローカル読取",
    "cloud_detail": "クラウド詳細を取得",
    "coverage": "記録された履歴の一部・完全性未確認",
    "empty": "この期間に記録済みの走行はありません",
    "read_error": "読み取れません。再読取するか期間を短くしてください。",
    "detail_error": "クラウド詳細を取得できません。後で再試行してください。",
    "loading": "読み取り中…",
    "next": "次のページ",
    "page": "ページ",
    "local": "ローカル履歴",
    "cloud": "クラウド詳細",
    "samples": "速度サンプル値・単位未確認",
    "unknown_units": "電力使用量・単位未確認",
    "observed": "観測時刻",
    "denied": "アクセスが拒否されました",
    "distance": "距離",
    "duration": "走行時間",
    "max_speed": "最高速度",
    "avg_speed": "平均速度",
    "energy": "電力量",
    "start": "開始時刻",
    "end": "終了時刻",
    "start_date": "開始日",
    "end_date": "終了日",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "未取得の月",
    "partial": "一部の月",
    "unknown": "不明な月",
    "source_fields": "Source field",
    "energy_intensity": "前回の走行: 距離あたりの消費電力",
    "track_points": "軌跡ポイント数",
    "distance_samples": "点間距離 · 単位未確認"
  },
  "ko": {
    "title": "주행 기록",
    "refresh": "로컬 읽기",
    "cloud_detail": "클라우드 상세 조회",
    "coverage": "저장된 일부 기록 · 완전성 미확인",
    "empty": "이 기간에 저장된 주행이 없습니다",
    "read_error": "읽기 실패. 다시 읽거나 기간을 줄이세요.",
    "detail_error": "클라우드 상세를 사용할 수 없습니다. 나중에 다시 시도하세요.",
    "loading": "읽는 중…",
    "next": "다음 페이지",
    "page": "페이지",
    "local": "로컬 기록",
    "cloud": "클라우드 상세",
    "samples": "속도 샘플값 · 단위 미확인",
    "unknown_units": "전기 사용량 · 단위 미확인",
    "observed": "관측 시간",
    "denied": "접근 거부",
    "distance": "거리",
    "duration": "주행 시간",
    "max_speed": "최고 속도",
    "avg_speed": "평균 속도",
    "energy": "에너지",
    "start": "시작 시간",
    "end": "종료 시간",
    "start_date": "시작 날짜",
    "end_date": "종료 날짜",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "누락된 월",
    "partial": "일부 월",
    "unknown": "알 수 없는 월",
    "source_fields": "Source field",
    "energy_intensity": "최근 주행: 거리당 에너지 소비",
    "track_points": "경로 지점 수",
    "distance_samples": "지점 간 거리 · 단위 미확인"
  },
  "nl": {
    "title": "Ritgeschiedenis",
    "refresh": "Lokaal lezen",
    "cloud_detail": "Clouddetails ophalen",
    "coverage": "Opgeslagen deel; volledigheid niet bevestigd",
    "empty": "Geen opgeslagen ritten in deze periode",
    "read_error": "Lezen mislukt. Lees opnieuw of verklein de periode.",
    "detail_error": "Clouddetails niet beschikbaar. Probeer later opnieuw.",
    "loading": "Lezen…",
    "next": "Volgende pagina",
    "page": "Pagina",
    "local": "Lokaal archief",
    "cloud": "Clouddetails",
    "samples": "Snelheidsmonsters · eenheid niet bevestigd",
    "unknown_units": "Elektriciteitsgebruik · eenheid niet bevestigd",
    "observed": "Waargenomen",
    "denied": "Toegang geweigerd",
    "distance": "Afstand",
    "duration": "Ritduur",
    "max_speed": "Maximumsnelheid",
    "avg_speed": "Gemiddelde snelheid",
    "energy": "Energie",
    "start": "Starttijd",
    "end": "Eindtijd",
    "start_date": "Begindatum",
    "end_date": "Einddatum",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Ontbrekende maanden",
    "partial": "Gedeeltelijke maanden",
    "unknown": "Onbekende maanden",
    "source_fields": "Source field",
    "energy_intensity": "Laatste rit: Energieverbruik per afstand",
    "track_points": "Routepunten",
    "distance_samples": "Afstanden tussen punten · eenheid niet bevestigd"
  },
  "pl": {
    "title": "Historia przejazdów",
    "refresh": "Odczytaj lokalnie",
    "cloud_detail": "Pobierz szczegóły z chmury",
    "coverage": "Zapisana część historii; kompletność niepotwierdzona",
    "empty": "Brak zapisanych przejazdów w tym zakresie",
    "read_error": "Błąd odczytu. Odczytaj ponownie lub skróć zakres.",
    "detail_error": "Szczegóły z chmury niedostępne. Spróbuj później.",
    "loading": "Odczyt…",
    "next": "Następna strona",
    "page": "Strona",
    "local": "Archiwum lokalne",
    "cloud": "Szczegóły z chmury",
    "samples": "Próbki prędkości · jednostka niepotwierdzona",
    "unknown_units": "Zużycie energii · jednostka niepotwierdzona",
    "observed": "Zaobserwowano",
    "denied": "Odmowa dostępu",
    "distance": "Dystans",
    "duration": "Czas przejazdów",
    "max_speed": "Prędkość maksymalna",
    "avg_speed": "Prędkość średnia",
    "energy": "Energia",
    "start": "Czas rozpoczęcia",
    "end": "Czas zakończenia",
    "start_date": "Data początkowa",
    "end_date": "Data końcowa",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Brakujące miesiące",
    "partial": "Niepełne miesiące",
    "unknown": "Nieznane miesiące",
    "source_fields": "Source field",
    "energy_intensity": "Ostatni przejazd: Zużycie energii na dystans",
    "track_points": "Punkty trasy",
    "distance_samples": "Odległości między punktami · jednostka niepotwierdzona"
  },
  "uk": {
    "title": "Історія поїздок",
    "refresh": "Прочитати локально",
    "cloud_detail": "Отримати деталі з хмари",
    "coverage": "Збережена частина історії; повноту не підтверджено",
    "empty": "У цьому діапазоні немає збережених поїздок",
    "read_error": "Помилка читання. Прочитайте знову або скоротіть діапазон.",
    "detail_error": "Деталі з хмари недоступні. Спробуйте пізніше.",
    "loading": "Читання…",
    "next": "Наступна сторінка",
    "page": "Сторінка",
    "local": "Локальний архів",
    "cloud": "Деталі з хмари",
    "samples": "Зразки швидкості · одиниці не перевірено",
    "unknown_units": "Споживання електрики · одиниці не перевірено",
    "observed": "Спостереження",
    "denied": "Доступ заборонено",
    "distance": "Відстань",
    "duration": "Тривалість поїздок",
    "max_speed": "Максимальна швидкість",
    "avg_speed": "Середня швидкість",
    "energy": "Енергія",
    "start": "Час початку",
    "end": "Час завершення",
    "start_date": "Початкова дата",
    "end_date": "Кінцева дата",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Відсутні місяці",
    "partial": "Неповні місяці",
    "unknown": "Невідомі місяці",
    "source_fields": "Source field",
    "energy_intensity": "Остання поїздка: Витрата енергії на відстань",
    "track_points": "Точки маршруту",
    "distance_samples": "Відстані між точками · одиниці не перевірені"
  },
  "tr": {
    "title": "Sürüş geçmişi",
    "refresh": "Yerel oku",
    "cloud_detail": "Bulut ayrıntısını al",
    "coverage": "Kayıtlı kısım; bütünlük doğrulanmadı",
    "empty": "Bu aralıkta kayıtlı sürüş yok",
    "read_error": "Okuma başarısız. Yeniden okuyun veya aralığı daraltın.",
    "detail_error": "Bulut ayrıntısı alınamadı. Daha sonra deneyin.",
    "loading": "Okunuyor…",
    "next": "Sonraki sayfa",
    "page": "Sayfa",
    "local": "Yerel arşiv",
    "cloud": "Bulut ayrıntısı",
    "samples": "Hız örnekleri · birim doğrulanmadı",
    "unknown_units": "Elektrik kullanımı · birim doğrulanmadı",
    "observed": "Gözlem zamanı",
    "denied": "Erişim reddedildi",
    "distance": "Mesafe",
    "duration": "Sürüş süresi",
    "max_speed": "En yüksek hız",
    "avg_speed": "Ortalama hız",
    "energy": "Enerji",
    "start": "Başlangıç zamanı",
    "end": "Bitiş zamanı",
    "start_date": "Başlangıç tarihi",
    "end_date": "Bitiş tarihi",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Eksik aylar",
    "partial": "Kısmi aylar",
    "unknown": "Bilinmeyen aylar",
    "source_fields": "Source field",
    "energy_intensity": "Son sürüş: Mesafe başına enerji tüketimi",
    "track_points": "Rota noktaları",
    "distance_samples": "Noktalar arası mesafe · birim doğrulanmadı"
  },
  "hi": {
    "title": "यात्रा इतिहास",
    "refresh": "स्थानीय पढ़ें",
    "cloud_detail": "क्लाउड विवरण लें",
    "coverage": "सहेजा गया आंशिक इतिहास; पूर्णता अपुष्ट",
    "empty": "इस अवधि में सहेजी गई यात्रा नहीं",
    "read_error": "पढ़ना विफल। फिर पढ़ें या अवधि घटाएँ।",
    "detail_error": "क्लाउड विवरण उपलब्ध नहीं। बाद में प्रयास करें।",
    "loading": "पढ़ रहा है…",
    "next": "अगला पृष्ठ",
    "page": "पृष्ठ",
    "local": "स्थानीय संग्रह",
    "cloud": "क्लाउड विवरण",
    "samples": "गति नमूने · इकाई अपुष्ट",
    "unknown_units": "बिजली उपयोग · इकाई अपुष्ट",
    "observed": "अवलोकन समय",
    "denied": "पहुँच अस्वीकृत",
    "distance": "दूरी",
    "duration": "यात्रा अवधि",
    "max_speed": "अधिकतम गति",
    "avg_speed": "औसत गति",
    "energy": "ऊर्जा",
    "start": "आरंभ समय",
    "end": "समाप्ति समय",
    "start_date": "आरंभ तिथि",
    "end_date": "अंतिम तिथि",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "अनुपस्थित महीने",
    "partial": "आंशिक महीने",
    "unknown": "अज्ञात महीने",
    "source_fields": "Source field",
    "energy_intensity": "पिछली यात्रा: प्रति दूरी ऊर्जा खपत",
    "track_points": "मार्ग बिंदु",
    "distance_samples": "बिंदुओं के बीच दूरी · इकाई अपुष्ट"
  },
  "id": {
    "title": "Riwayat perjalanan",
    "refresh": "Baca lokal",
    "cloud_detail": "Ambil detail cloud",
    "coverage": "Riwayat sebagian tersimpan; kelengkapan belum terverifikasi",
    "empty": "Tidak ada perjalanan tersimpan dalam rentang ini",
    "read_error": "Pembacaan gagal. Baca ulang atau persempit rentang.",
    "detail_error": "Detail cloud tidak tersedia. Coba lagi nanti.",
    "loading": "Membaca…",
    "next": "Halaman berikutnya",
    "page": "Halaman",
    "local": "Arsip lokal",
    "cloud": "Detail cloud",
    "samples": "Sampel kecepatan · satuan belum terverifikasi",
    "unknown_units": "Penggunaan listrik · satuan belum terverifikasi",
    "observed": "Diamati",
    "denied": "Akses ditolak",
    "distance": "Jarak",
    "duration": "Durasi perjalanan",
    "max_speed": "Kecepatan maksimum",
    "avg_speed": "Kecepatan rata-rata",
    "energy": "Energi",
    "start": "Waktu mulai",
    "end": "Waktu selesai",
    "start_date": "Tanggal mulai",
    "end_date": "Tanggal akhir",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Bulan belum tersedia",
    "partial": "Bulan sebagian",
    "unknown": "Bulan tidak diketahui",
    "source_fields": "Source field",
    "energy_intensity": "Perjalanan terakhir: Konsumsi energi per jarak",
    "track_points": "Titik lintasan",
    "distance_samples": "Jarak antar titik · satuan belum diverifikasi"
  },
  "th": {
    "title": "ประวัติการเดินทาง",
    "refresh": "อ่านในเครื่อง",
    "cloud_detail": "ดูรายละเอียดคลาวด์",
    "coverage": "ประวัติที่บันทึกไว้บางส่วน ยังไม่ยืนยันความครบถ้วน",
    "empty": "ไม่มีการเดินทางที่บันทึกในช่วงนี้",
    "read_error": "อ่านไม่สำเร็จ กรุณาอ่านใหม่หรือลดช่วงวันที่",
    "detail_error": "รายละเอียดคลาวด์ไม่พร้อมใช้งาน ลองใหม่ภายหลัง",
    "loading": "กำลังอ่าน…",
    "next": "หน้าถัดไป",
    "page": "หน้า",
    "local": "คลังในเครื่อง",
    "cloud": "รายละเอียดคลาวด์",
    "samples": "ตัวอย่างความเร็ว · ยังไม่ยืนยันหน่วย",
    "unknown_units": "การใช้ไฟฟ้า · ยังไม่ยืนยันหน่วย",
    "observed": "เวลาที่รับข้อมูล",
    "denied": "ไม่มีสิทธิ์เข้าถึง",
    "distance": "ระยะทาง",
    "duration": "ระยะเวลาเดินทาง",
    "max_speed": "ความเร็วสูงสุด",
    "avg_speed": "ความเร็วเฉลี่ย",
    "energy": "พลังงาน",
    "start": "เวลาเริ่ม",
    "end": "เวลาสิ้นสุด",
    "start_date": "วันที่เริ่มต้น",
    "end_date": "วันที่สิ้นสุด",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "เดือนที่ขาด",
    "partial": "เดือนบางส่วน",
    "unknown": "เดือนที่ไม่ทราบ",
    "source_fields": "Source field",
    "energy_intensity": "การเดินทางล่าสุด: การใช้พลังงานต่อระยะทาง",
    "track_points": "จุดเส้นทาง",
    "distance_samples": "ระยะระหว่างจุด · ยังไม่ยืนยันหน่วย"
  },
  "vi": {
    "title": "Lịch sử chuyến đi",
    "refresh": "Đọc cục bộ",
    "cloud_detail": "Lấy chi tiết đám mây",
    "coverage": "Lịch sử đã lưu một phần; chưa xác minh tính đầy đủ",
    "empty": "Không có chuyến đi đã lưu trong khoảng này",
    "read_error": "Đọc thất bại. Đọc lại hoặc thu hẹp khoảng ngày.",
    "detail_error": "Chi tiết đám mây chưa khả dụng. Thử lại sau.",
    "loading": "Đang đọc…",
    "next": "Trang tiếp theo",
    "page": "Trang",
    "local": "Kho cục bộ",
    "cloud": "Chi tiết đám mây",
    "samples": "Mẫu tốc độ · đơn vị chưa xác minh",
    "unknown_units": "Điện sử dụng · đơn vị chưa xác minh",
    "observed": "Thời gian ghi nhận",
    "denied": "Truy cập bị từ chối",
    "distance": "Quãng đường",
    "duration": "Thời gian di chuyển",
    "max_speed": "Tốc độ tối đa",
    "avg_speed": "Tốc độ trung bình",
    "energy": "Năng lượng",
    "start": "Giờ bắt đầu",
    "end": "Giờ kết thúc",
    "start_date": "Ngày bắt đầu",
    "end_date": "Ngày kết thúc",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "Tháng thiếu",
    "partial": "Tháng một phần",
    "unknown": "Tháng chưa xác định",
    "source_fields": "Source field",
    "energy_intensity": "Chuyến gần nhất: Năng lượng tiêu thụ trên quãng đường",
    "track_points": "Điểm lộ trình",
    "distance_samples": "Khoảng cách giữa các điểm · chưa xác minh đơn vị"
  },
  "ar": {
    "title": "سجل الرحلات",
    "refresh": "قراءة محلية",
    "cloud_detail": "جلب تفاصيل السحابة",
    "coverage": "جزء محفوظ من السجل؛ الاكتمال غير مؤكد",
    "empty": "لا توجد رحلات محفوظة في هذه الفترة",
    "read_error": "فشلت القراءة. أعد القراءة أو ضيّق الفترة.",
    "detail_error": "تفاصيل السحابة غير متاحة. حاول لاحقاً.",
    "loading": "جارٍ القراءة…",
    "next": "الصفحة التالية",
    "page": "الصفحة",
    "local": "الأرشيف المحلي",
    "cloud": "تفاصيل السحابة",
    "samples": "عينات السرعة · الوحدة غير مؤكدة",
    "unknown_units": "استخدام الكهرباء · الوحدة غير مؤكدة",
    "observed": "وقت الرصد",
    "denied": "الوصول مرفوض",
    "distance": "المسافة",
    "duration": "مدة الرحلات",
    "max_speed": "السرعة القصوى",
    "avg_speed": "متوسط السرعة",
    "energy": "الطاقة",
    "start": "وقت البدء",
    "end": "وقت الانتهاء",
    "start_date": "تاريخ البداية",
    "end_date": "تاريخ النهاية",
    "cursor_error": "The continuation expired, was evicted, or belongs to another vehicle/range. Start again.",
    "ride_id": "Ride ID",
    "missing": "أشهر مفقودة",
    "partial": "أشهر جزئية",
    "unknown": "أشهر غير معروفة",
    "source_fields": "Source field",
    "energy_intensity": "آخر رحلة: استهلاك الطاقة لكل مسافة",
    "track_points": "نقاط المسار",
    "distance_samples": "المسافات بين النقاط · الوحدة غير مؤكدة"
  }
};
